//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }

        [Required(ErrorMessage = "請填寫職稱")]
        [StringLength(10, ErrorMessage = "職稱長度上限為10個字元")]
        public string 職稱 { get; set; }

        [Required(ErrorMessage = "請填寫姓名")]
        [StringLength(10, ErrorMessage = "姓名長度上限為10個字元")]
        public string 姓名 { get; set; }

        [Required(ErrorMessage = "請填寫Email")]
        [EmailAddress(ErrorMessage = "請確認Email格式是否正確")]
        public string Email { get; set; }

        [Required(ErrorMessage = "請填寫手機")]
        [RegularExpression(@"^09\d{2}-?\d{6}$", ErrorMessage = "請確認手機格式是否正確")]
        public string 手機 { get; set; }

        [Required(ErrorMessage = "請填寫電話")]
        [RegularExpression(@"^0\d{1}-?\d{8}$", ErrorMessage = "請確認電話格式是否正確")]
        public string 電話 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
